destination: ./_site
auto:        false
lsi:         false
server_port: 4000
markdown:    maruku
permalink: /news/:title/
pygments: true
paginate: 5
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
  
exclude: ["Rakefile"]